openapi: 3.0.0
info:
  title: 'Bus Ticket RESTful API Documentation'
  description: 'Bus Ticket RESTful API Documentation'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: tafiaalifianty@students.itb.ac.id
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000/api/v1'
    description: 'Demo API server'
paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: 'Login to user account'
      description: 'Login to user account'
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: 'Login success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'
        400:
          description: 'Bad request'
        405:
          description: 'Method not allowed (Unauthenticated)'
        500:
          description: 'Internal server error'
  /auth/register:
    post:
      tags:
        - Authentication
      summary: 'Register new account'
      description: 'Register new account'
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        200:
          description: 'Register success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'
        400:
          description: 'Bad request'
        405:
          description: 'Method not allowed (Unauthenticated)'
        500:
          description: 'Internal server error'
  /auth/logout:
    post:
      tags:
        - Authentication
      summary: 'Logout auth session'
      description: 'Logout auth session'
      operationId: logout
      responses:
        200:
          description: 'User successfully signed out'
        405:
          description: 'Method not allowed (Unauthenticated)'
        500:
          description: 'Internal server error'
      security:
        -
          bearerAuth: []
  /auth/refresh:
    post:
      tags:
        - Authentication
      summary: 'Refresh JWT token'
      description: 'Refresh JWT token'
      operationId: refresh
      responses:
        200:
          description: 'Refresh token success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'
        405:
          description: 'Method not allowed (Unauthenticated)'
        500:
          description: 'Internal server error'
      security:
        -
          bearerAuth: []
  /auth/me:
    get:
      tags:
        - Authentication
      summary: 'Get authenticated''s user data'
      description: 'Get authenticated''s user data'
      operationId: me
      responses:
        200:
          description: 'User data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        405:
          description: 'Method not allowed (Unauthenticated)'
        500:
          description: 'Internal server error'
      security:
        -
          bearerAuth: []
  /pembelian/1:
    get:
      tags:
        - Order
      summary: 'Get order detail'
      description: 'Get order detail'
      operationId: order/id
      responses:
        200:
          description: 'Order data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        404:
          description: 'Data not found'
        405:
          description: 'Method not allowed (Unauthenticated)'
        500:
          description: 'Internal server error'
      security:
        -
          bearerAuth: []
    post:
      tags:
        - Order
      summary: 'Create order'
      description: 'Create order'
      operationId: order/user_id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        200:
          description: 'Order data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        400:
          description: 'Validation errors'
        405:
          description: 'Method not allowed (Unauthenticated)'
        500:
          description: 'Internal server error'
      security:
        -
          bearerAuth: []
  /pembayaran/1:
    post:
      tags:
        - Payment
      summary: 'Create payment'
      description: 'Create payment'
      operationId: payment/order_id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        200:
          description: 'Payment data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        400:
          description: 'Validation errors'
        404:
          description: 'Data not found'
        405:
          description: 'Method not allowed (Unauthenticated)'
        500:
          description: 'Internal server error'
      security:
        -
          bearerAuth: []
  /ticket/1:
    get:
      tags:
        - Ticket
      summary: 'Get ticket detail'
      description: 'Get ticket detail'
      operationId: ticket/id
      responses:
        200:
          description: 'Ticket data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        404:
          description: 'Data not found'
        405:
          description: 'Method not allowed (Unauthenticated)'
        500:
          description: 'Internal server error'
      security:
        -
          bearerAuth: []
  /ticket/user/1:
    get:
      tags:
        - Ticket
      summary: 'Get user''s ticket'
      description: 'Get user''s ticket'
      operationId: ticket/user/user_id
      responses:
        200:
          description: 'Ticket data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        404:
          description: 'Data not found'
        405:
          description: 'Method not allowed (Unauthenticated)'
        500:
          description: 'Internal server error'
      security:
        -
          bearerAuth: []
  /users/1:
    get:
      tags:
        - User
      summary: 'Get user detail'
      description: 'Get user detail'
      operationId: user/id
      responses:
        200:
          description: 'User data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: 'Data not found'
        405:
          description: 'Method not allowed (Unauthenticated)'
        500:
          description: 'Internal server error'
      security:
        -
          bearerAuth: []
components:
  schemas:
    LoginRequest:
      title: 'Login Request'
      description: 'Login request body data'
      required:
        - email
        - password
      properties:
        email:
          title: email
          description: 'Email of the user'
          type: string
          example: johndoe@mail.com
        password:
          title: password
          description: 'Password of the user'
          type: string
          example: yourpassword
      type: object
    OrderRequest:
      title: 'Order Request'
      description: 'Order request body data'
      properties:
        bus_name:
          title: bus_name
          description: 'Bus name'
          type: string
          example: 'Sumber Selamat'
        ticket_amount:
          title: ticket_amount
          description: 'Amount of the ticket'
          type: integer
          example: 1
        seat_position:
          title: seat_position
          description: 'Seat position'
          type: string
          example: A1
        departure_city:
          title: departure_city
          description: 'Departure city'
          type: string
          example: Surabaya
        departure_bus_station:
          title: departure_bus_station
          description: 'Departure bus station name'
          type: string
          example: Purabaya
        departure_date:
          title: departure_date
          description: 'Departure date time'
          type: string
          format: date-time
          example: '2020-11-27 01:55:43'
        arrived_city:
          title: arrived_city
          description: 'Arrived city'
          type: string
          example: Yogyakarta
        arrived_bus_station:
          title: arrived_bus_station
          description: 'Arrived bus station name'
          type: string
          example: Lempuyangan
        arrived_date:
          title: arrived_date
          description: 'Arrived date time'
          type: string
          format: date-time
          example: '2020-11-27 01:55:43'
        total_price:
          title: total_price
          description: 'Total price'
          type: integer
          example: 12000
      type: object
    PaymentRequest:
      title: 'Payment Request'
      description: 'Payment request body data'
      required:
        - email
        - password
      properties:
        payment_amount:
          title: payment_amount
          description: 'Amount of payment'
          type: integer
          example: 12000
        payment_proof:
          title: payment_proof
          description: 'Image of payment proof'
          type: string
          example: 'base64:image'
        bank_name:
          title: bank_name
          description: 'Name of the bank'
          type: string
          example: Mandiri
        bank_account:
          title: bank_account
          description: 'Bank account'
          type: string
          example: '123456789'
      type: object
    RegisterRequest:
      title: 'Register Request'
      description: 'Register request body data'
      required:
        - email
        - password
        - password_confirmation
        - age
        - city
      properties:
        email:
          title: email
          description: Email
          type: string
          example: johndoe@mail.com
        password:
          title: password
          description: Password
          type: string
          example: yourpassword
        password_confirmation:
          title: password_confirmation
          description: 'Password confirmation'
          type: string
          example: yourpassword
        age:
          title: age
          description: Age
          type: integer
          example: 18
        city:
          title: city
          description: City
          type: string
          example: 'Los Angeles'
      type: object
    Auth:
      title: Auth
      description: 'Auth model'
      properties:
        access_token:
          title: 'Access token'
          description: 'JWT access token'
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL3YxL2F1dGgvbG9naW4iLCJpYXQiOjE2MDY0NTc2MDksImV4cCI6MTYwNjQ2MTIwOSwibmJmIjoxNjA2NDU3NjA5LCJqdGkiOiJBY29DeWJrRUN2dVdnRjA4Iiwic3ViIjoxLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.ImW2CEVjdNxEYaVA-bVUc5wFL5IyPbuXIxeIep_QzKo
        token_type:
          title: 'Token type'
          description: 'Authentication token type'
          type: string
          example: bearer
        expires_in:
          title: 'Expires in'
          description: 'Token expires duration'
          type: integer
          example: 3600
        user:
          title: User
          description: 'User data'
      type: object
      xml:
        name: Auth
    Order:
      title: Order
      description: 'Order model'
      properties:
        id:
          title: ID
          description: ID
          type: integer
          format: int64
          example: 1
        user_id:
          title: 'User ID'
          description: 'User ID'
          type: string
          example: 1
        total_price:
          title: 'Total price'
          description: 'Total price'
          type: integer
          example: 12000
        status:
          title: Status
          description: 'Order status'
          type: string
          example: waiting_payment
        created_at:
          title: 'Created at'
          description: 'Created at'
          type: string
          format: datetime
          example: '2020-11-27 01:55:43'
        updated_at:
          title: 'Updated at'
          description: 'Updated at'
          type: string
          format: datetime
          example: '2020-11-27 01:55:43'
      type: object
      xml:
        name: Order
    Payment:
      title: Payment
      description: 'Payment model'
      properties:
        id:
          title: ID
          description: ID
          type: integer
          format: int64
          example: 1
        user_id:
          title: 'User ID'
          description: 'User ID'
          type: string
          example: 1
        order_id:
          title: 'Order ID'
          description: 'Order ID'
          type: string
          example: 1
        payment_amount:
          title: 'Total amount'
          description: 'Total amount'
          type: integer
          example: 12000
        payment_proof:
          title: 'Payment proof'
          description: 'URL of image of payment proof'
          type: string
          example: 'http://localhost/images/12345678.png'
        bank_name:
          title: 'Bank name'
          description: 'Bank name'
          type: string
          example: Mandiri
        bank_account:
          title: 'Bank account'
          description: 'Bank account'
          type: string
          example: '123456789'
        created_at:
          title: 'Created at'
          description: 'Created at'
          type: string
          format: datetime
          example: '2020-11-27 01:55:43'
        updated_at:
          title: 'Updated at'
          description: 'Updated at'
          type: string
          format: datetime
          example: '2020-11-27 01:55:43'
      type: object
      xml:
        name: Payment
    Ticket:
      title: Ticket
      description: 'Ticket model'
      properties:
        id:
          title: ID
          description: ID
          type: integer
          format: int64
          example: 1
        user_id:
          title: 'User ID'
          description: 'User ID'
          type: string
          example: 1
        order_id:
          title: 'Order ID'
          description: 'Order ID'
          type: string
          example: 1
        bus_name:
          title: bus_name
          description: 'Bus name'
          type: string
          example: 'Sumber Selamat'
        ticket_amount:
          title: ticket_amount
          description: 'Amount of the ticket'
          type: integer
          example: 1
        seat_position:
          title: seat_position
          description: 'Seat position'
          type: string
          example: A1
        departure_city:
          title: departure_city
          description: 'Departure city'
          type: string
          example: Surabaya
        departure_bus_station:
          title: departure_bus_station
          description: 'Departure bus station name'
          type: string
          example: Purabaya
        departure_date:
          title: departure_date
          description: 'Departure date time'
          type: string
          format: date-time
          example: '2020-11-27 01:55:43'
        arrived_city:
          title: arrived_city
          description: 'Arrived city'
          type: string
          example: Yogyakarta
        arrived_bus_station:
          title: arrived_bus_station
          description: 'Arrived bus station name'
          type: string
          example: Lempuyangan
        arrived_date:
          title: arrived_date
          description: 'Arrived date time'
          type: string
          format: date-time
          example: '2020-11-27 01:55:43'
        total_price:
          title: total_price
          description: 'Total price'
          type: integer
          example: 12000
        created_at:
          title: 'Created at'
          description: 'Created at'
          type: string
          format: datetime
          example: '2020-11-27 01:55:43'
        updated_at:
          title: 'Updated at'
          description: 'Updated at'
          type: string
          format: datetime
          example: '2020-11-27 01:55:43'
      type: object
      xml:
        name: Ticket
    User:
      title: User
      description: 'User model'
      properties:
        id:
          title: ID
          description: ID
          type: integer
          format: int64
          example: 1
        name:
          title: Name
          description: 'Name of the user'
          type: string
          example: 'John Doe'
        email:
          title: Email
          description: 'Email of the user'
          type: string
          example: johndoe@mail.com
        email_verified_at:
          title: 'Email verified datetime'
          description: 'Email verified datetime of the user'
          type: string
          format: datetime
          example: '2020-11-27 01:55:43'
        age:
          title: Age
          description: 'Age of the user'
          type: integer
          example: '1'
        city:
          title: City
          description: 'City of the user'
          type: string
          example: 'Los Angeles'
        created_at:
          title: 'Created at'
          description: 'Created at'
          type: string
          format: datetime
          example: '2020-11-27 01:55:43'
        updated_at:
          title: 'Updated at'
          description: 'Updated at'
          type: string
          format: datetime
          example: '2020-11-27 01:55:43'
      type: object
      xml:
        name: User
  securitySchemes:
    bearerAuth:
      type: http
      name: bearerAuth
      in: header
      bearerFormat: JWT
      scheme: bearer
tags:
  -
    name: Authentication
    description: 'All authentication methods (login, register, logout, etc)'
  -
    name: User
    description: 'All about users'
  -
    name: Order
    description: 'All about orders'
  -
    name: Payment
    description: 'All about payments'
  -
    name: Ticket
    description: 'All about ticket'
security:
  - []
